Repository open-algebra/Oasis, pull requests merged in 2024-02, with the labels that each got.

#54 Simplify ClangFormat Workflow
  .github/workflows/clang-format.yml
  include/Oasis/Add.hpp
Labels: optimization

#58 Remove Redundant Add Cases
  src/Add.cpp
Labels: optimization

#46 [Bugfix] associativity
  src/Add.cpp
  src/Divide.cpp
  src/Multiply.cpp
  tests/AddTests.cpp
  tests/DivideTests.cpp
  tests/MultiplyTests.cpp
Labels: bug, enhancement

#66 Use Graphviz to generate SVG graphs
  .github/workflows/doxygen.yml
  Doxyfile
Labels: documentation
